# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\IntroAlgoritmo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class IntroAlgoritmo(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 853)
        MainWindow.setMinimumSize(QtCore.QSize(1129, 853))
        MainWindow.setMaximumSize(QtCore.QSize(1129, 853))
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 10, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 20, 771, 67))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 100, 241, 67))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(320, 260, 261, 51))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(320, 310, 612, 131))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(330, 410, 610, 120))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(330, 540, 292, 33))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(80, 580, 939, 153))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(80, 270, 231, 301))
        self.label_12.setStyleSheet("border-image: url(InfoImages/selectionsortnew.png);")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("InfoImages/selectionsortnew.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(80, 150, 771, 66))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(80, 240, 649, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(80, 210, 781, 21))
        self.label_15.setObjectName("label_15")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(830, 560, 271, 61))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("InfoImages/complejidadalgo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 750, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 15px;\n"
"border-width: 5px; \n"
"    border-style: solid;  \n"
"    border-color: black;")
        self.pushButton.setObjectName("pushButton")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_9.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">ALGORITMO SELECTION SORT</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">¿Qué es?</span></p><p align=\"justify\"><br/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">¿Cómo funciona?</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:10pt; font-style:italic;\">El algoritmo divide el arreglo en dos partes:</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">1. </span><span style=\" font-size:10pt; font-weight:600;\">Subarreglo ordenado: </span><span style=\" font-size:10pt;\">Inicialmente vacío y crece en cada iteración.</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">2. </span><span style=\" font-size:10pt; font-weight:600;\">Subarreglo desordenado: </span><span style=\" font-size:10pt;\">Contiene los elementos que aún deben ordenarse.</span></p><p align=\"justify\"><br/></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:10pt; font-style:italic;\">Pasos en cada iteración:</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">1. Encuentra el menor elemento en el subarreglo desordenado.</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">2. Intercambia este elemento con el primer elemento del subarreglo desordenado.</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">3. Amplía el subarreglo ordenado moviendo el límite entre las dos partes.</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Análisis del algoritmo</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">Complejidad temporal</span><span style=\" font-size:10pt;\">: Siempre realiza n−1,n−2,...,1n−1,n−2,...,1 comparaciones, resultando en:</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">Esto lo hace ineficiente para grandes arreglos.</span></p><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">Complejidad espacial</span><span style=\" font-size:10pt;\">: Solo requiere espacio adicional para algunas variables (O(1)O(1)), lo que </span></p><p align=\"justify\"><span style=\" font-size:10pt;\">lo convierte en un algoritmo en sitio (in-place).</span></p><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">Estabilidad</span><span style=\" font-size:10pt;\">: No es estable, ya que los intercambios pueden alterar el orden relativo de elementos iguales.</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:10pt;\">El </span><span style=\" font-size:10pt; font-weight:600;\">Selection Sort</span><span style=\" font-size:10pt;\"> es un algoritmo de ordenación que organiza los elementos de un arreglo </span></p><p align=\"justify\"><span style=\" font-size:10pt;\">seleccionando iterativamente el menor (o mayor) y colocándolo en su posición correcta.<br/></span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Es útil para aprender los conceptos básicos de ordenación gracias a su enfoque directo.</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Es simple, pero ineficiente para grandes conjuntos de datos debido a su complejidad de tiempo de O(n</span><span style=\" font-size:10pt; vertical-align:super;\">2</span><span style=\" font-size:10pt;\">)</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "¡MIRALO EN ACCIÓN!"))
